@startuml
class Station{
    Object Food 
    boolean Occupied
}
class Frying_Station{
    void flip()
}
class Cutting_Station{
    void cut(Object Ingredient)
}
class Ingredient_Station{
    string food:output
    void output()
}
class Bin{
    void Delete(Object food)
}

class Counter{
    boolean verify_order()
}

Station <|-- Frying_Station
Station <|-- Cutting_Station
Station <|-- Ingredient_Station
Station <|-- Bin
Station <|-- Counter
@enduml