' Preview with Alt D
' Sequence diagram for crafting meals from ingredients
@startuml
skinparam titleBorderRoundCorner 15
skinparam titleBorderThickness 2
skinparam titleBorderColor red
title Crafting\nRecipie

actor Active_Chef as Chef
participant Stack as Inventory
entity Craft_Prompt as GUI
entity Recipie_List as Recipies

' Checking stack for a valid combination of items that can be crafted into a meal
group Checking_Stack
    loop while True
        Inventory -> Recipies : Check(Stack)
        note left: if Inventory is updated
        Chef <- Recipies : Boolean [True/False]
        alt Valid Recipie (True)
        Inventory -> GUI : Prompt users to craft
        note left: If Inventory contains all ingredients for a valid recipie
        Chef -> GUI : Craft(Stack)
        note left: Exits loop after Chef starts crafting
        end
    end
end

' Crafting meal out of ingredients in the stack
group Craft_Item
    Inventory -> Recipies : Craft(Stack)
    note left: Passes prepared ingredients on
    Chef <- Recipies : Stack <- Updated_Stack
    note left: Stack now returns the crafted meal
end

@enduml