@startuml
' Preview with Alt D
' Date: 05-01-2023
@startgantt
hide ressources names
skinparam classFontSize 5
'Main Goals
[Team Forming] lasts 7 days and is colored in Plum/Green
[Requirements Elicitation] lasts 10 days and is colored in Plum/Green
[Risk Assessment and Mitigation] lasts 11 days and is colored in Plum/Green
[Method Selection & Planning] lasts 16 days and is colored in Plum/Green
[Design Architecture] lasts 39 days and is colored in Plum/Orange
[Implementation] lasts 37 days and is colored in Plum/Orange
Project starts 2022-11-09
[Team Forming] starts 2022-11-09
[Requirements Elicitation] starts 2022-11-16
[Method Selection & Planning] starts 2022-12-07
[Risk Assessment and Mitigation] starts 2022-11-26
[Design Architecture] starts 2022-12-01
[Implementation] starts 2022-12-14

'Requirements
[Research Requirements] lasts 7 days and is colored in Lavender/Green and starts after [Requirements Elicitation]'s start
[Research Website] on {Craig:50%} lasts 1 days and is colored in Lavender/Green and starts after [Research Requirements]'s start
[Research Game Engines] on {Jack:33%}{Kamrul:33%}{Eliash:33%} lasts 2 days and is colored in Lavender/Green and starts after [Research Requirements]'s start
[Interview Preparation] on {Chase:30%}{Callum:30%}{Jack:10%}{Kamrul:10%}{Eliash:10%}{Craig:10%} lasts 7 days and is colored in Lavender/Green and starts after [Research Requirements]’s start
[Interview Completed] happens at [Interview Preparation]’s end

[Requirement Elicitation Process Explanation] on {Craig:100%} lasts 3 days and is colored in Lavender/Green and starts after [Interview Completed]'s end
[Formatting User & System Requirements] on {Callum:25%}{Jack:25%}{Kamrul:25%}{Chase:25%} lasts 3 days and is colored in Lavender/Green and starts after [Interview Completed]'s end
[Requirements Completed] happens at [Formatting User & System Requirements]’s end

'Risk Assessment and Mitgation
[Risk Management Process] on {Callum:100%} lasts 11 days and is colored in Lavender/Green and starts after [Risk Assessment and Mitigation]'s start
[Constructing Risk Register] on {Callum:75%}{Craig:25%} lasts 11 days and is colored in Lavender/Green and starts after [Risk Assessment and Mitigation]'s start
[Risk Assessment Completed] happens at [Constructing Risk Register]’s end

'Method Selection & Planning
[Engineering Methods] on {Jack:100%} lasts 7 days and is colored in Lavender/Green and starts after [Method Selection & Planning]'s start
[Team Approach] on {Jack:50%} lasts 8 days and is colored in Lavender/Green and starts after [Method Selection & Planning]'s start
[Systematic Project Plan] on {Craig:50%} lasts 8 days and is colored in Lavender/Green and starts after [Method Selection & Planning]'s start
[Method Planning Complete] happens at [Systematic Project Plan]’s end

'Design Architecture
[UML Class Diagrams] on {Kamrul:50%}{Chase:50%} lasts 22 days and is colored in Lavender/Green and starts 5 days after [Risk Assessment and Mitigation]'s start
[Architecture Write-Up] lasts 15 days and is coloured in Lavender/Orange and starts 10 days after [UML Class Diagrams]'s end
[Assets experimentation] on {Callum:100%} lasts 7 days and is colored in Lavender/Green and starts 6 days after [UML Class Diagrams]'s start
[Assets pack made] happens at [Assets experimentation]’s end

'Misc
[Catch-Up Meeting] happens at [Architecture Write-Up]'s start
[Documentation Review] on {Craig:50%}{Jack:50%} lasts 6 days and is colored in Lavender/Orange and starts after [Catch-Up Meeting]'s start
[Updating Website] on {Callum:50%}{Kamrul:50%} lasts 6 days and is colored in Lavender/Orange and starts after [Catch-Up Meeting]'s start

'Implementation
[LibGDX experimentation] on {Chase:100%} lasts 9 days and is colored in Lavender/Green and starts after [Implementation]'s start
[Implementation Sprint] on {Chase:50%} lasts 11 days and is colored in Lavender/Orange and starts after [LibGDX experimentation]'s end

'Breaks
2022/12/23 to 2023/01/02 are colored in lightblue
2022/12/23 to 2023/01/02 are named [Winter Break]
2022/12/23 to 2023/01/02 are closed

2023/01/09 to 2023/01/13 are colored in LightGoldenRodYellow
2023/01/09 to 2023/01/13 are named [Exam Week]
2023/01/09 to 2023/01/13 are closed

@endgantt
@enduml