@startuml 
class Person{

}
class Cook{
    stack itemsHeld
    void move(String Direction)
    void interact()
    void pick_up()
    void place_down()
    void craft()
    void swapCook()
}
class Customer{
    Object generateOrder()
}
Person <|-- Cook
Person <|-- Customer
@enduml