@startuml 
class Person{

}
class Cook{
    stack Items_held
    void Move(String Direction)
    void Interact()
    void Swap_cook()
}
class Customer{
    Object Generate_Order()
}
Person <|-- Cook
Person <|-- Customer
@enduml