@startuml
class Station{
    object food
    boolean occupied
}
class FryingStation{
    void flip()
}
class CuttingStation{
    void cut()
}
class IngredientStation{
    string food
    object output_food()
}
Class Bin{
    void delete(Object food)
}
class NonInteractiveStation{}
Station <|-- FryingStation
Station <|-- CuttingStation
Station <|-- IngredientStation
Station <|-- Bin
Station <|-- NonInteractiveStation
@enduml