' Preview with Alt D
' Sequence diagram for Frying ingredients using hob
@startuml
skinparam titleBorderRoundCorner 15
skinparam titleBorderThickness 2
skinparam titleBorderColor red
title Frying\nIngredients

actor Active_Chef as Chef
participant Stack as Inventory
entity Frying_Station as Hob
entity Bin as Bin

' Attempting to Fry Item
group Frying_Item
    Chef -> Hob : Place(Stack[Head])
    note left: if Station is empty
    Inventory -> Hob : Item
    Chef -> Hob : Hob() 
    note left: if Item is Fryable
    ' Successful Fry
    alt Fried Well
        Hob -> Hob : Item -> \nFried Item
        note left: if Item left cooking for long enough
        Chef -> Hob : Grab(Stack) 
        note left: if Station is not empty \n&  Stack not full
        Inventory <- Hob : Fried Item
    ' Overcooked Item
    else Overcooked
        Hob -> Hob : Item -> \nOvercooked Item
        note left: if Item left cooking for too long
        Chef -> Hob : Grab(Stack) 
        note left: if Station is not empty \n&  Stack not full
        Inventory <- Hob : Overcooked Item
        Chef -> Bin : Place(Stack[Head]])
        Inventory -> Bin : Overcooked Item
    else Undercooked
        Hob -> Hob : Item -> \nItem
        note left: if Item not left cooking for long enough
        Chef -> Hob : Grab(Stack) 
        note left: if Station is not empty \n&  Stack not full
        Inventory <- Hob : Item
    end
end
@enduml